export const watchlistMock = {
    60625: {
        timestamp: 1636665554062,
        progress: 600,
        active: true,
        show: {
            backdrop_path: "/7DE67DzAlZmCOm1OYnAL7gV1B8w.jpg",
            first_air_date: "2013-12-02",
            genre_ids: [16, 35, 10765, 10759],
            id: 60625,
            name: "Rick and Morty",
            origin_country: ["US"],
            original_language: "en",
            original_name: "Rick and Morty",
            overview:
                "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
            popularity: 442.88,
            poster_path: "/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg",
            vote_average: 8.8,
            vote_count: 5714,
        },
    },
    93405: {
        timestamp: 1636825542373,
        progress: 0,
        active: true,
        show: {
            backdrop_path: "/qw3J9cNeLioOLoR68WX7z79aCdK.jpg",
            genre_ids: [10759, 9648, 18],
            id: 93405,
            original_language: "ko",
            poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
            name: "Squid Game",
            vote_average: 7.8,
            original_name: "오징어 게임",
            origin_country: ["KR"],
            vote_count: 8800,
            overview:
                "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
            first_air_date: "2021-09-17",
            popularity: 1920.829,
            media_type: "tv",
        },
    },
    94605: {
        timestamp: 1636825829091,
        progress: 0,
        active: true,
        show: {
            vote_average: 9.1,
            vote_count: 292,
            id: 94605,
            original_name: "Arcane",
            origin_country: ["US"],
            backdrop_path: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
            genre_ids: [16, 10765, 10759],
            overview:
                "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
            original_language: "en",
            poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
            name: "Arcane",
            first_air_date: "2021-11-06",
            popularity: 932.116,
            media_type: "tv",
        },
    },
    131927: {
        timestamp: 1636825831625,
        progress: 0,
        active: true,
        show: {
            backdrop_path: "/e6v08948EZVvLrx0sWpmglguY9e.jpg",
            genre_ids: [18, 80],
            id: 131927,
            original_language: "en",
            poster_path: "/9EBKgrFIsCFSV1RZKWhYUdbtGiv.jpg",
            name: "Dexter: New Blood",
            vote_average: 9.1,
            original_name: "Dexter: New Blood",
            origin_country: ["US"],
            vote_count: 91,
            overview:
                "10 years after Dexter went missing in the eye of Hurricane Laura, we find him living under an assumed name in the small town of Iron Lake, New York.  Dexter may be embracing his new life, but in the wake of unexpected events in this close-knit community, his Dark Passenger beckons.",
            first_air_date: "2021-11-07",
            popularity: 615.446,
            media_type: "tv",
        },
    },
};
